name: Deploy VPC Module

on:
  workflow_dispatch:

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init

      - name: Read previous S3 outputs (for dependencies)
        run: |
          export OUTPUT_S3_BUCKET=tf-monitoring-output-dev
          export OUTPUT_S3_KEY=module-outputs/latest.json
          python3 ../../scripts/read_module_outputs.py

      - name: Plan VPC
        run: terraform plan -target=module.vpc

      - name: Apply VPC
        run: terraform apply -target=module.vpc -auto-approve

      - name: Push module outputs to S3
        run: |
          export OUTPUT_S3_BUCKET=tf-monitoring-output-dev
          python3 ../../scripts/push_module_outputs.py
